export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  admin: {
    users: '/admin/users',
    user: (id: string) => `/admin/users/${id}`,
    lockUser: (id: string) => `/admin/users/${id}/lock`,
    unlockUser: (id: string) => `/admin/users/${id}/unlock`,
    resetUserPassword: (id: string) => `/admin/users/${id}/reset-password`,
    suppliers: '/admin/suppliers',
    supplier: (id: string) => `/admin/suppliers/${id}`,
    approveSupplier: (id: string) => `/admin/suppliers/${id}/approve`,
    rejectSupplier: (id: string) => `/admin/suppliers/${id}/reject`,
    supplierFee: (id: string) => `/admin/suppliers/${id}/fee`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    dashboard: '/admin/dashboard',
    logistics: '/admin/logistics',
    logisticsOperator: (id: string) => `/admin/logistics/${id}`,
    activateOperator: (id: string) => `/admin/logistics/${id}/activate`,
    deactivateOperator: (id: string) => `/admin/logistics/${id}/deactivate`,
    zones: '/admin/zones',
    zone: (id: string) => `/admin/zones/${id}`,
    districts: '/admin/districts',
  },
  products: {
    list: '/products',
    search: '/products/search',
    detail: (id: string) => `/products/${id}`,
    supplierProducts: '/supplier/products',
  },
  categories: '/categories',
  orders: {
    create: '/orders',
    list: '/orders',
    detail: (id: string) => `/orders/${id}`,
    cancel: (id: string) => `/orders/${id}/cancel`,
    confirmReceipt: (id: string) => `/orders/${id}/confirm-receipt`,
  },
  addresses: {
    list: '/addresses',
    create: '/addresses',
    detail: (id: string) => `/addresses/${id}`,
    setDefault: (id: string) => `/addresses/${id}/default`,
  },
  districts: '/districts',
  distributionPoint: {
    profile: '/distribution-point/profile',
  },
  vouchers: {
    validate: '/vouchers/validate',
  },
  logistics: {
    shipments: '/logistics/shipments',
    accept: (id: string) => `/logistics/shipments/${id}/accept`,
    updateStatus: (id: string) => `/logistics/shipments/${id}/status`,
    complete: (id: string) => `/logistics/shipments/${id}/complete`,
  },
} as const
